### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by Alastorial** [g2arepo/glory-to-aurora#1]
**Описание бага**
 При загрузке работы из json файла работа загружается, но ее нельзя сохранить. При нажатии ctrl+S так же высвечивается ошибка (см ниже). При переходе во вкладку исходный код отсутствуют какие-либо файлы. Работа 4_1_1.

**Воспроизведение бага**
1. Открываем задачу, запускаем загрузку файла, после окончания процесса высвечивается предупреждение о несохраненных данных
2. Нажимаем "да", открывается работа, полностью заполненная из файла json, но отсутствует все во вкладке Исходный код. (Так же появляются две ошибки "Task is found")
3. При нажатии ctrl+S высвечивается та же ошибка
4. При переходе в исходный код - все отсутствует

**Логи из отладки**
В конце лог, который был после попытки сейва
//del

**Скриншоты**
Отсутствие кода:
![image](https://user-images.githubusercontent.com/55281727/160694040-cd5d8b36-0088-457d-b765-76cd6396d6d1.png)
Ошибки при сейве (по одной от каждой попытки):
![image](https://user-images.githubusercontent.com/55281727/160694363-025cf79d-7d65-4035-bb70-01c0002f63f4.png)

**Исходник**
//del

**Comment by g2arepo** [comment]
Спасибо) Я глянул, косяк не в Авроре, а в том, что фитча не до конца была допилена. Аврора мало того, что ID задачи хранит в json-е, так еще и не бекапит исходники

Релизнул 1.2, где все пофикшено, но 4_1_1 придется пересохранить, чтобы работа полностью скопировалась

**Comment by Alastorial** [comment]
Получается, крутой, спасибо, что быстро пофиксил :)

**Comment by alexbewion** [comment]
Я попробовал загрузить старый json файл на новой версии - на экране просто квадрат с текстом "Загрузка задачи". Для новой версии изменили json файлы для загрузки? Спрашиваю, потому что та работа, с которой сгружен джсон находится на проверке и я не могу с нее сгрузить. 

P. s. здесь описывается способ получения доступа к работам, которые находятся на стадии проверки, с чистой авророй это работает, сделал то же самое с твоей - не реагирует ( 
https://mirea.ninja/t/revers-inzhiniring-programmy-aco-avrora-ishodniki-kak-vstavlyat-tekst-v-avroru/1244 - способ №2
