### ISSUE TITLE
Возможное дополнение.

### ISSUE THREAD

**Issue by Alastorial** [g2arepo/glory-to-aurora#2]
**Дополнительный функционал**

Привет, было бы здорово иметь возможность открывать работу в тот момент, когда она отправлена на проверку, но еще не проверена. Данную задачу решили на том же форуме - https://mirea.ninja/t/revers-inzhiniring-programmy-aco-avrora-ishodniki-kak-vstavlyat-tekst-v-avroru/1244. К слову, проделал те же вещи в коде с твоей версией и оно не сработало.

**Comment by g2arepo** [comment]
> **Дополнительный функционал**
> 
> Привет, было бы здорово иметь возможность открывать работу в тот момент, когда она отправлена на проверку, но еще не проверена. Данную задачу решили на том же форуме - https://mirea.ninja/t/revers-inzhiniring-programmy-aco-avrora-ishodniki-kak-vstavlyat-tekst-v-avroru/1244. К слову, проделал те же вещи в коде с твоей версией и оно не сработало.

Привет, да, и правда не открывается. Это скорее баг, ибо задумывалось, что работу можно открыть всегда, а я накосячил с условием в коде.

Модуль заданий заменен скриптом, поэтому замена кода старого модуля никак не влияет) Код скрипта же обфусцирован, так что так же что-то переписать не выйдет (точнее, выйдет, но это неудобно)

Короче, я поправил, в новом релизе вместе с наследованием классов все будет) Если надо срочно эту фитчу, то в папке Script можешь заменить JS-файл на этот для фикса: https://www.upload.ee/download/14012777/3fa392c65ed81accd6fc/g2a-script.js
