### ISSUE TITLE
Ошибка при генерации метода и алгоритма с подключенными библиотеками

### ISSUE THREAD

**Issue by JosukeBukin** [g2arepo/glory-to-aurora#3]
**Описание бага**
При нажатии на "Сгенерировать методы из исходников" или "Сгенерировать методы из исходников" сначала появляется окно сохранения этих самых исходников, а затем ошибка:
```
Скрипт не смог скомпилировать ваш код. Проверьте его на правильность. Ошибки:
'string' file not found
```

**Воспроизведение бага**
1. Добавить в исходники `#include <string>`
2. Нажмите на "Сгенерировать методы из исходников" или "Сгенерировать методы из исходников" 
3. Получаем ошибки

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/24449271/161259069-0372c6de-ebf3-465d-9520-ddc512d66219.png)

**Comment by g2arepo** [comment]
Привет. Есть такая проблема: встроенный компилятор не содержит include файлов, так что по-хорошему нужно поставить Visual Studio (и C++ компоненты внутри установщика Visual Studio), и проблема решится. Ну или LLVM: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/LLVM-14.0.0-win64.exe

Issue пока не закрываю:
TODO: пересобрать libclangsharp и докинуть include-файлы вместе со скриптом

**Comment by g2arepo** [comment]
Фикс в 1.3
