### ISSUE TITLE
алгоритм и метод

### ISSUE THREAD

**Issue by asd3rt** [g2arepo/glory-to-aurora#8]
когда нажимаю кнопку, создать метдоды по исходникам, или создать алгоритм по исходникам, то мне выдает ошибку:
Скрипт не смог скомпилировать ваш код. Проверьте его на правильность. Ошибки:
'iostream' file not found
хотя #include <iostream> написан везде

**Comment by Snow4DV** [comment]
Привет. Есть такая проблема: встроенный компилятор не содержит include файлов, так что по-хорошему нужно поставить Visual Studio (и C++ компоненты внутри установщика Visual Studio), и проблема решится. Ну или LLVM: https://releases.llvm.org/download.html#14.0.0

**Comment by g2arepo** [comment]
Привет. Есть такая проблема: встроенный компилятор не содержит include файлов, так что по-хорошему нужно поставить Visual Studio (и C++ компоненты внутри установщика Visual Studio), и проблема решится. Ну или LLVM: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/LLVM-14.0.0-win64.exe

**Comment by g2arepo** [comment]
Повтор #3 (кликабельно) - дальнейшее обсуждение можно продолжить там, если установка LLVM или Visual Studio не поможет
